timeout: 60
region: "ap-northeast-1"
role_name: "arn:aws:iam::905450884640:role/pianosystem-lambda-role"
utils_role_name: "arn:aws:iam::905450884640:role/pianosystem-lambda-utils-role"
subnets_id1: "subnet-00b3482ab3f5733e0"
subnets_id2: "subnet-0e94a4812195abd0a"
securityGroupId: "sg-0b390104331b2f465"
db_name: "postgres"
db_host: "localhost"
db_port: 5432
db_username: "postgres"
db_password: "admin@123"
s3_log_bucket: "rikai-dev-pianosystem-log-bucket"
log_groups: "/aws/lambda/pianosystem-dev-main"